environment:
  name: test
  project: cdf-bootcamp-62-test
  validation-type: test
  selected:
    - modules/bootcamp/data_foundation
    - modules/bootcamp/ice_cream_api
    - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space

      data_foundation:
        data_developer_source_id: 0d4bad78-26ec-4e2e-9868-5dda4bb8ded4

      ice_cream_api:        
        icapi_extractors_source_id: 2c245d43-2829-450a-9076-de78afc24704
        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_trigger_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_trigger_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
        icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}

      use_cases:
        oee:
          data_pipeline_oee_source_id: ca040809-f113-45dc-aba7-4dfc352cf13e
          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
          data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}
